### ISSUE TITLE
testing in macos (some comments)

### ISSUE THREAD

**Issue by fdch** [katjav/pd-mouse-trial#1]
Hi Katja, 

I just tried this in OSX 10.14.3 (18D109)

Mi first reaction: It is *quite* nice!! very useful and everything seems to work as expected. Although it is slightly strange at first to get accustomed, because it seems like a different animal than the rest of the `pd` thingies.

Here are some comments, hope they are useful:

-  I dont see why the properties box is different from the rest of iemgui. I know it's an abstraction by design, but it would be more consistent to have all gui properties look similar (again, if this is considered gui) (edit: ok, I see why, and perhaps it would be a matter of making all tk dialogs abstractions :) 

-  Is`key` + `hover|drag` possible as well?

-  I tested usage on the big patch, and hovering on the printing mousepad gave me exponential Wish CPU usage as I (nervously) make circles faster and faster (but only up to 50%, no more) Here's a screenshot:

![Screen Shot 2019-03-19 at 17 19 37](https://user-images.githubusercontent.com/13335792/54624117-12465280-4a6d-11e9-85e1-df4e775a9449.png)

Thanks!!

Fede

**Comment by katjav** [comment]
Thanks for your feedback Fede.

`key + hover | drag` is not likely to become a convenience feature of a mouse tracking class since key event classes are already available and a user can combine the data at will.

The CPU load you see when hovering over the printing mousepad is mostly due to the printing activity in Pd window. And the print object is merely there to verify that hover events are indeed received by the objects. If hovering over the 'silent' objects doesn't generate substantial CPU load, that is a good sign.

**Comment by fdch** [comment]
great! yes, that only happens with the printing then :)
